/* 
 * iter.c: part of fivetwoplus libraries
 *
 * iter-sequences are single-element only (like the ones generated by io.lines).
 *    iter{10,20,30} ~~> 1; 2; 3
 *    iter{alpha=true,beta=true,gamma=true} ~~> alpha; beta; gamma
 *
 * 1. iter(obj, [factory=pairs]) honors __iter
 *    else uses supplied factory, its results will be clipped to 
 *    their first element only
 *
 */

#include <lua.h>
#include <lauxlib.h>

#define LUA_FIVETWO_PLUS
#include "fivetwo.h"


/* This could have been done with an __index metamethod for
 * strings, but that's already been used up by the string library.
 */
static int strnext (lua_State *L) {
    /* stack[1] = LUA_TSTRING; stack[2] = Integer */
    size_t len;
    /* const char *s = lua_tolstring(L, 1, &len); */
    const char *s = luaL_checklstring(L, 1, &len);
    lua_Integer i = luaL_checkinteger(L, 2);
    i++;  /* next value */
    if (i > 0 && (size_t)i <= len) {
        lua_pushinteger(L, i);
        lua_pushlstring(L, s + i - 1, 1);
        return 2;
    }
    return 0;
}


/* Requires gen as upvalue(1), stack[1]=state, stack[2]=key */
static int luaIter_arg1 (lua_State *L) {
  lua_settop(L, 2);
  lua_pushvalue(L, lua_upvalueindex(1));
  lua_insert(L, 1);
  lua_call(L, 2, 1);
  return 1;
}



/* Requires luaB_pairs as upvalue(1) */
static int luaIter_iter (lua_State *L) {
    if (luaL_getmetafield(L, 1, "__iter")) {
      lua_pushvalue(L, 1);  /* argument 'self' to metamethod */
      lua_call(L, 1, 3);  /* get 3 values from metamethod */
      return 3;
    }
    /* use arg[2] or luaB_pairs, wrapping gen with arg1() */
    if (lua_isnoneornil(L, 2)) {
        lua_settop(L, 1);
        lua_pushvalue(L, lua_upvalueindex(1));
    }
    else {
        lua_settop(L, 2);
    }
    lua_pushvalue(L, 1);  /* argument 'self' to factory */
    /* stack= obj, factory, obj */
    lua_call(L, 1, 3); /* get 3 values from factory */
    /* stack= obj, gen, ret2, ret3 */
    if (!lua_isfunction(L, 2)) {
        return luaL_error(L, "attempt to call a %s value", luaL_typename(L, 2)); 
    }
    lua_pushvalue(L, 2);
    /* push arg1() with gen as upvalue */
    lua_pushcclosure(L, luaIter_arg1, 1);
    /* stack: obj, gen, ret2, ret3, arg1() */
    lua_replace(L, 2);
    return 3;
}


extern int luaopen_fivetwo_iter (lua_State *L) {
    lua_getglobal(L, "pairs");  /* iter needs pairs as upvalue */
    lua_pushcclosure(L, luaIter_iter, 1);
    lua_setglobal(L, "iter");
    return 0;
}
